source 'https://rubygems.org'

gem 'cucumber'
gem 'cucumber-core'
gem 'cucumber-wire'
gem 'gherkin'
gem 'rspec'
gem 'rspec-core'
gem 'rspec-expectations'
gem 'rspec-mocks'
gem 'rspec-support'
gem 'selenium-webdriver'
gem 'watir'
gem 'watir-webdriver'
